nSetLang = {};
if XEBPlusLanguage == "en-US" then
    nSetLang[1] = "neutrino Launcher Settings"
    nSetLang[2] = "Configure neutrino Launcher menu"
    nSetLang[3] = "Disable game specific artwork in menu."
    nSetLang[4] = "Disable loading and other messages\nthat appear at the bottom of the screen."
    nSetLang[5] = "Highlighted game's icon will not rotate."
    nSetLang[6] = "Refresh artwork cache next time the\n menu is launched."
    nSetLang[7] = "Delete and re-copy all cached files.\nWARNING: This can take a very long\ntime."
    nSetLang[8] = "Disable Artwork"
    nSetLang[9] = "Disable Status Messages"
    nSetLang[10] = "Disable Auto-Recache"
    nSetLang[11] = "Refresh Artwork Cache"
    nSetLang[12] = "Cache Refresh Queued"
    nSetLang[13] = "Rebuild Artwork Cache"
    nSetLang[14] = "Cache Rebuild Queued"
    nSetLang[15] = "Disable Icon Animation"
    nSetLang[16] = "Enable neutrino Launcher (HDD) plugin.\nRequires XEB+ refresh."
    nSetLang[17] = "Enable neutrino Launcher (USB) plugin.\nRequires XEB+ refresh."
    nSetLang[18] = "Enable neutrino Launcher (MX4SIO) plugin.\nRequires XEB+ refresh."
    nSetLang[19] = "Enable HDD"
    nSetLang[20] = "Enable USB"
    nSetLang[21] = "Enable MX4ISO"
    nSetLang[22] = "Show game title IDs in the menu."
    nSetLang[23] = "Show game version numbers in the menu."
    nSetLang[24] = "Show game media type in the menu."
    nSetLang[25] = "Show Title ID"
    nSetLang[26] = "Show Version"
    nSetLang[27] = "Show Media"
    nSetLang[28] = "Disable Background Fading"
    nSetLang[29] = "Disable the fade effect when loading\nbackgound artwork."
    nSetLang[30] = "Enable neutrino Launcher (UDPBD) plugin.\nRequires XEB+ refresh."
    nSetLang[31] = "Enable UDPBD"
    nSetLang[32] = "Clean Artwork Cache"
    nSetLang[33] = "Delete unused files in the artwork cache."
elseif XEBPlusLanguage == "es-419" then
    nSetLang[1] = "Configuración del lanzador neutrino"
    nSetLang[2] = "Configurar el menú del lanzador de neutrino"
    nSetLang[3] = "Desactiva el arte específico del juego en\nel menú."
    nSetLang[4] = "Deshabilitar la carga y otros mensajes que\naparecen en la parte inferior de la pantalla."
    nSetLang[5] = "Desactiva la animación del icono de giro\ndel disco en el menú"
    nSetLang[6] = "Actualizar el caché de arte la próxima vez\nque se inicie el menú."
    nSetLang[7] = "Elimine y vuelva a copiar todos los\narchivos almacenados en caché.\nADVERTENCIA: Esto puede llevar mucho\ntiempo."
    nSetLang[8] = "Deshabilitar arte"
    nSetLang[9] = "Deshabilitar mensajes de estado"
    nSetLang[10] = "Deshabilitar la reconst. del caché automática"
    nSetLang[11] = "Actualizar caché de arte"
    nSetLang[12] = "Actualización de caché en cola"
    nSetLang[13] = "Reconstruir la caché de arte"
    nSetLang[14] = "Encolada la reconstrucción del caché"
    nSetLang[15] = "Desactivar animación de iconos"
    nSetLang[16] = "Habilite el complemento neutrino Launcher (HDD).\nRequiere actualización XEB+."
    nSetLang[17] = "Habilite el complemento neutrino Launcher (USN).\nRequiere actualización XEB+."
    nSetLang[18] = "Habilite el complemento neutrino Launcher (MX4SIO).\nRequiere actualización XEB+."
    nSetLang[19] = "Habilitar disco duro"
    nSetLang[20] = "Habilitar USB"
    nSetLang[21] = "Habilitar MX4SIO"
    nSetLang[22] = "Muestra los ID de los títulos del juego en el menú."
    nSetLang[23] = "Muestra los números de versión del juego en el menú."
    nSetLang[24] = "Muestra el tipo de media del juego en el menú."
    nSetLang[25] = "Mostrar ID del Título"
    nSetLang[26] = "Mostrar Versión"
    nSetLang[27] = "Mostrar Media"
    nSetLang[28] = "Desactivar el desvanecimiento del fondo."
    nSetLang[29] = "Desactiva el efecto de desvanecimiento\nal cargar ilustraciones de fondo."
    nSetLang[30] = "Habilite el complemento neutrino Launcher (UDPBD).\nRequiere actualización XEB+."
    nSetLang[31] = "Habilitar UDPBD"
    nSetLang[32] = "Limpiar caché de ilustraciones"
    nSetLang[33] = "Elimine los archivos no utilizados en el caché\nde ilustraciones."
elseif XEBPlusLanguage == "pt-BR" then
    nSetLang[1] = "Configurações do neutrino Launcher"
    nSetLang[2] = "Configurar menu do neutrino Launcher"
    nSetLang[3] = "Desative a artwork específica do jogo\nno menu."
    nSetLang[4] = "Desative o carregamento e outras\nmensagens que apareçam na parte\ninferior do ecrã."
    nSetLang[5] = "Desative a animação do ícone  do\ndisco no menu"
    nSetLang[6] = "Atualize a cache de artwork na próxima\nvez que o menu for iniciado."
    nSetLang[7] = "Apague e copie novamente todos os\nficheiros em cache.\nAVISO: Isto pode levar muito tempo."
    nSetLang[8] = "Desativar artwork"
    nSetLang[9] = "Desativar mensagens de estado"
    nSetLang[10] = "Desativar o recache automático"
    nSetLang[11] = "Atualizar cache de artwork"
    nSetLang[12] = "Atualização de cache em espera..."
    nSetLang[13] = "Reconstruir cache de artwork"
    nSetLang[14] = "Reconstrução de cache em espera..."
    nSetLang[15] = "Desativar animação de ícones"
    nSetLang[16] = "Ative o plugin neutrino Launcher (HDD).\nRequer atualização XEB+."
    nSetLang[17] = "Ative o plugin neutrino Launcher (USB).\nRequer atualização XEB+."
    nSetLang[18] = "Ative o plugin neutrino Launcher (MX4SIO).\nRequer atualização XEB+."
    nSetLang[19] = "Habilitar HDD"
    nSetLang[20] = "Habilitar USB"
    nSetLang[21] = "Habilitar MX4SIO"
    nSetLang[22] = "Mostrar IDs de títulos de jogos no menu."
    nSetLang[23] = "Mostre os números da versão do jogo no menu."
    nSetLang[24] = "Mostrar o tipo de Mídia do jogo no menu."
    nSetLang[25] = "Mostrar ID do Título"
    nSetLang[26] = "Mostrar Versão"
    nSetLang[27] = "Mostrar Mídia"
    nSetLang[28] = "Desativar desvanecimento de fundo."
    nSetLang[29] = "Desative o efeito de desvanecimento\nao carregar arte de fundo."
    nSetLang[30] = "Ative o plugin neutrino Launcher (UDPBD).\nRequer atualização XEB+."
    nSetLang[31] = "Habilitar UDPBD"
    nSetLang[32] = "Limpar cache de arte"
    nSetLang[33] = "Apague os ficheiros não utilizados do cache de arte."
end

PluginData = {};
PluginData.Type = "LuaScript";
PluginData.Category = 6;
PluginData.Name = nSetLang[1];
PluginData.Description = nSetLang[2];
PluginData.Safe = true;
PluginData.ValueA = "APPS/neutrinoLauncher/settings.lua";
PluginData.ValueB = "NONE";
PluginData.ValueC = "NONE";
if theXEBPlusVersion == "XEBPLUS-2022-09" then -- If using the XEB+ Xmas showcase, an external icon will be loaded
	PluginData.Icon = 70; -- Preventive, in case the game files' are missing
	if System.doesFileExist(System.currentDirectory().."THM/"..loadedTheme.."/ic_set_neutrino_cfg.png") then
			AddIcon=#themeInUse+1
			themeInUse[AddIcon] = Graphics.loadImage(System.currentDirectory().."THM/"..loadedTheme.."/ic_set_neutrino_cfg.png")
			PluginData.Icon = AddIcon;
	elseif System.doesFileExist(System.currentDirectory().."APPS/neutrinoLauncher/image/ic_set_neutrino_cfg.png") then
		AddneutrinosethdlIcon=#themeInUse+1
		themeInUse[AddneutrinosethdlIcon] = Graphics.loadImage(System.currentDirectory().."APPS/neutrinoLauncher/image/ic_set_neutrino_cfg.png")
		PluginData.Icon = AddneutrinosethdlIcon;
	end
else -- Else, the icon will be loaded from XEB+'s theme
	PluginData.Icon = 70;
end
